export enum FamilySituation {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
  SEPARATED = 'SEPARATED',
  DOMESTIC_PARTNERSHIP = 'DOMESTIC_PARTNERSHIP',
  REMARRIED = 'REMARRIED',
  COMMON_LAW_MARRIAGE = 'COMMON_LAW_MARRIAGE',
  ANNULLED = 'ANNULLED',
  OTHER = 'OTHER'
}
